FitHub/FitHub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FitHubManageApp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FitHub/FitHubManageApp/urls.py
from FitHubManageApp.views import SuperAdminDashBoardView, AdministratorCreateView, AdministratorUpdateView, \
    AdministratorDeleteView, \
    AdministratorListView, TrainerCreateView, TrainerDeleteView, TrainerListView, \
    LogoutView, UserLogin, ChangePasswordView, TrainerDashBoardView, AdminDashBoardView, GymInformationCreateView, \
    GymInformationUpdateView, GymInfoDeleteView, GymInformationListView, TrainerUpdateView, AdminVideoListView, \
    AdminVideoCreateView, AdminVideoUpdateView, AdminVideoDeleteView, AdminBlogCreateView, AdminBlogUpdateView, \
    AdminBlogListView, AdminBlogDeleteView, AdminBlogDetailView, AdminPaymentPlanCreateView, AdminPaymentPlanUpdateView, \
    AdminPaymentPlanDeleteView, AdminPaymentPlanListView, AdminEquipmentUpdateView, AdminEquipmentCreateView, \
    AdminEquipmentDeleteView, AdminEquipmentListView, AdminEquipmentDetailView, UserRegisterView, \
    GymMembershipPaymentCreate, UserAdminDashBoardView, gym_equipment_order_ajax_view

from django.urls import path

urlpatterns = [
    path('superadmin/dashboard', SuperAdminDashBoardView.as_view(), name='superadmin_dashboard'),
    path('user/dashboard', UserAdminDashBoardView.as_view(), name='user_dashboard'),
    # superadmin section - GymCreation
    path('superadmin/gyminfo/create/', GymInformationCreateView.as_view(), name='superadmin_gym_create'),
    path('superadmin/gyminfo/update/<int:pk>', GymInformationUpdateView.as_view(), name='superadmin_gym_update'),
    path('superadmin/gyminfo/delete/<int:pk>', GymInfoDeleteView.as_view(), name='superadmin_gym_delete'),
    path('superadmin/gyminfo/list/', GymInformationListView.as_view(), name='superadmin_gym_list'),

    # Admin Section
    path('user/admin/create/<int:gym_id>', AdministratorCreateView.as_view(), name='fithub_admin_create'),
    path('user/admin/update/<int:pk>', AdministratorUpdateView.as_view(), name='fithub_admin_update'),
    path('user/admin/delete/<int:pk>', AdministratorDeleteView.as_view(), name='fithub_admin_delete'),
    path('user/admin/list/<int:gym_id>', AdministratorListView.as_view(), name='fithub_admin_list'),
    path('user/admin/dashboard', AdminDashBoardView.as_view(), name='fithub_admin_dashboard'),

    # Trainer Section
    path('user/trainer/create/', TrainerCreateView.as_view(), name='fithub_trainer_create'),
    path('user/trainer/update/<int:pk>', TrainerUpdateView.as_view(), name='fithub_trainer_update'),
    path('user/trainer/delete/<int:pk>', TrainerDeleteView.as_view(), name='fithub_trainer_delete'),
    path('user/trainer/list/', TrainerListView.as_view(), name='fithub_trainer_list'),
    path('user/trainer/dashboard', TrainerDashBoardView.as_view(), name='fithub_trainer_dashboard'),

    # Admin Video Management
    path('user/admin/video/create/', AdminVideoCreateView.as_view(), name='fithub_admin_video_create'),
    path('user/admin/video/update/<int:pk>', AdminVideoUpdateView.as_view(), name='fithub_admin_video_update'),
    path('user/admin/video/delete/<int:pk>', AdminVideoDeleteView.as_view(), name='fithub_admin_video_delete'),
    path('user/admin/video/list/', AdminVideoListView.as_view(), name='fithub_admin_video_list'),

    # Admin Blog Management
    path('user/admin/blog/create/', AdminBlogCreateView.as_view(), name='fithub_admin_blog_create'),
    path('user/admin/blog/update/<int:pk>', AdminBlogUpdateView.as_view(), name='fithub_admin_blog_update'),
    path('user/admin/blog/delete/<int:pk>', AdminBlogDeleteView.as_view(), name='fithub_admin_blog_delete'),
    path('user/admin/blog/detail/<int:pk>', AdminBlogDetailView.as_view(), name='fithub_admin_blog_detailview'),
    path('user/admin/blog/list/', AdminBlogListView.as_view(), name='fithub_admin_blog_list'),


    # Admin PaymentPlan Management
    path('user/admin/payment/plan/create/', AdminPaymentPlanCreateView.as_view(), name='fithub_admin_payment_plan_create'),
    path('user/admin/payment/plan/update/<int:pk>', AdminPaymentPlanUpdateView.as_view(), name='fithub_admin_payment_plan_update'),
    path('user/admin/payment/plan/delete/<int:pk>', AdminPaymentPlanDeleteView.as_view(), name='fithub_admin_payment_plan_delete'),
    path('user/admin/payment/plan/list/', AdminPaymentPlanListView.as_view(), name='fithub_admin_payment_plan_list'),

    # Add Gym Equipments
    path('user/admin/equipment/create/', AdminEquipmentCreateView.as_view(), name='fithub_admin_equipment_create'),
    path('user/admin/equipment/update/<int:pk>', AdminEquipmentUpdateView.as_view(), name='fithub_admin_equipment_update'),
    path('user/admin/equipment/delete/<int:pk>', AdminEquipmentDeleteView.as_view(), name='fithub_admin_equipment_delete'),
    path('user/admin/equipment/detail/<int:pk>', AdminEquipmentDetailView.as_view(), name='fithub_admin_equipment_detailview'),
    path('user/admin/equipment/list/', AdminEquipmentListView.as_view(), name='fithub_admin_equipment_list'),
    path('user/user/equipment/order_ajax_view/', gym_equipment_order_ajax_view, name='fithub_order_placed_for_equipment_ajax'),

    # User Payment
    path('user/payment/', GymMembershipPaymentCreate.as_view(), name='fithub_user_payment'),




    # Login Section
    path('register', UserRegisterView.as_view(), name='fithub_user_register_view'),
    path('', UserLogin.as_view(), name='fithub_login_view'),
    path('logout', LogoutView.as_view(), name='fithub_logout_view'),
    path('user/admins/change_password/', ChangePasswordView.as_view(), name='fithub_administrators_password_change'),



]

FitHub/FitHubManageApp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class FitHubMember(models.Model):
    Male = "Male"
    Female = "Female"
    Others = "Others"
    GenderChoices = (
        (Male, "Male"),
        (Female, "Female"),
        (Others, "Others"),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    sex = models.CharField(choices=GenderChoices, max_length=10, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    plan = models.ForeignKey('Plan', on_delete=models.CASCADE, null=True, blank=True)
    payment_status = models.BooleanField(default=False)
    joining_date = models.DateTimeField(auto_now=True)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    plan_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}"


class Plan(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    duration = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class GymInformation(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100, unique=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    instagram = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)
    logo = models.ImageField(upload_to='gym_information/', null=True, blank=True,
                             default='gym_information/logo.png')
    about_us = models.TextField(blank=True, null=True)
    members = models.ManyToManyField(User, related_name='gym_members', null=True, blank=True)

    def __str__(self):
        return self.name


class AdminGymGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='gym_gallery/', null=True, blank=True, default='gym_gallery/gym_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.name)


class GymMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    is_trainer = models.BooleanField(default=False)
    is_normal_member = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"


class GymAdministator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


class GymTrainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


class AdminVideoGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.name)


class Equipments(models.Model):
    name = models.CharField(max_length=512, default='')
    description = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='equipments/', null=True, blank=True, default='equipments/equipment_image.png')
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return "{}".format(self.name)


class EquipmentOrder(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='equipments/', null=True, blank=True, default='equipments/equipment_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    user = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now=True)


class Payment(models.Model):
    member = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    payment_date = models.DateTimeField(auto_now=True)
    plan = models.ForeignKey('Plan', on_delete=models.CASCADE)


class GymMemberVideoGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.name)


class WorkoutVideo(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)


class DietChart(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='diet_chart/', null=True, blank=True, default='diet_chart/diet_chart_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)
    member = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    diet_chart_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)


class Blog(models.Model):
    title = models.CharField(max_length=512)
    image = models.ImageField(upload_to='blog/', null=True, blank=True, default='blog/blog_image.png')
    admin = models.ForeignKey(GymAdministator, on_delete=models.CASCADE)
    description = models.TextField()
    blog_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.title)

class BuyEquipment(models.Model):
    count = models.IntegerField(default=1)
    user = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now=True)
    equipment = models.ForeignKey('Equipments', on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.name)

FitHub/FitHubManageApp/templates/FitHubManageApp/Account/change_password.html
{% extends 'adminlte/base.html' %}
{% block title %}IGCAR{% endblock %}
{% block content %}

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Change Password</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" action="">
            {% csrf_token %}
            {#            {{ form.as_p }}#}
            <div class="card-body">
                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Change</button>
            </div>
        </form>
    </div>
{% endblock %}

FitHub/FitHubManageApp/templates/FitHubManageApp/Account/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FitHub | Login</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
    <style>
        .errorlist {
            color: red;
        }

        .login_hub {
            background-image: url('https://img.freepik.com/premium-photo/side-motion-view-sexy-fit-athlete-running-girl-sportswear-street-front-grey-wall_232070-2642.jpg?w=740');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center; /* Adjust as needed */
            background-attachment: fixed; /* Optional: prevents scrolling */
        }
    </style>
    {{ form.media.css }}
</head>
<body class="hold-transition login-page login_hub">
<div class="login-box">
  <div class="login-logo">
      <a href="#" style="color:lavenderblush"><b>FitHub</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form action="" method="post">
          {% csrf_token %}
          <p style="color: #dc0032;">{{ error }}</p>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="User Name" name="username" id="id_username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password" id="id_password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
         {% comment %} <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                <a href="{% url 'fithub_user_register_view' %}"> <button class="btn btn-primary btn-block">SignUp</button></a>
                Remember Me
              </label>
            </div>
          </div>{% endcomment %}
          <!-- /.col -->
          <div class="col-4">
             {% comment %} <button  class="btn btn-primary btn-block">{% endcomment %}<a class="btn btn-primary btn-block" href="{% url 'fithub_user_register_view' %}" >SignUp</a>{% comment %}</button>{% endcomment %}
          </div>
          <div class="col-4">

          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      {% comment %}<p class="mb-1">
        <a href="#">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="#" class="text-center">Register a new membership</a>
      </p>{% endcomment %}
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>

FitHub/FitHubManageApp/templates/FitHubManageApp/Account/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FitHub | Login</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
    <style>
        .errorlist {
            color: red;
        }

        .register_hub {
            background-image: url('https://img.freepik.com/free-photo/low-angle-view-unrecognizable-muscular-build-man-preparing-lifting-barbell-health-club_637285-2497.jpg?w=740&t=st=1691552524~exp=1691553124~hmac=f57fe5530001750a82e140207e5e86ff35f358a5b1a5684162a6aae942b1317f');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center; /* Adjust as needed */
            background-attachment: fixed; /* Optional: prevents scrolling */
        }
    </style>
    {{ form.media.css }}
</head>
<body class="hold-transition login-page register_hub">
<div class="login-box">
    <div class="login-logo">
        <a href="#" style="color: white"><b>FitHub</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Register To Fithub</p>
            <form action="" method="post">
                {% csrf_token %}
                {#                  <p style="color: #dc0032;">{{ error }}</p>#}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="First Name" name="first_name"
                           id="id_first_name">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name" id="id_last_name">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <p>{{ form.email.errors }}</p>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email" name="email" id="id_email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <p>{{ form.password.errors }}</p>
                <div class="input-group mb-3">

                    <input type="password" class="form-control" placeholder="Password" name="password" id="id_password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>

                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password"
                           id="id_confirm_password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <label for="id_plan_name">Choose Your Plan</label>
                    <select class="form-control rounded-0" id="id_plan_name" name="plan_name">
                        <option value="Basic Plan">Basic</option>
                        <option value="Premium Plan">Premium</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Address" name="address" id="id_address">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-home"></span>
                        </div>

                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Mobile" name="phone" id="id_phone">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <a href="{% url 'fithub_login_view' %}"  {% comment %}class="btn btn-primary btn-block"{% endcomment %}>Sign
                            In</a>
                    </div>
                    <div class="col-4">
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">REGISTER</button>
                    </div>


                    <!-- /.col -->
                    <!-- /.col -->
                </div>
            </form>

            {% comment %}<p class="mb-1">
        <a href="#">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="#" class="text-center">Register a new membership</a>
      </p>{% endcomment %}
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>