FitHub/FitHub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FitHubManageApp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FitHub/FitHubManageApp/urls.py
from FitHubManageApp.views import SuperAdminDashBoardView, AdministratorCreateView, AdministratorUpdateView, \
    AdministratorDeleteView, \
    AdministratorListView, TrainerCreateView, TrainerDeleteView, TrainerListView, \
    LogoutView, UserLogin, ChangePasswordView, TrainerDashBoardView, AdminDashBoardView, GymInformationCreateView, \
    GymInformationUpdateView, GymInfoDeleteView, GymInformationListView, TrainerUpdateView, AdminVideoListView, \
    AdminVideoCreateView, AdminVideoUpdateView, AdminVideoDeleteView, AdminBlogCreateView, AdminBlogUpdateView, \
    AdminBlogListView, AdminBlogDeleteView, AdminBlogDetailView, AdminPaymentPlanCreateView, AdminPaymentPlanUpdateView, \
    AdminPaymentPlanDeleteView, AdminPaymentPlanListView, AdminEquipmentUpdateView, AdminEquipmentCreateView, \
    AdminEquipmentDeleteView, AdminEquipmentListView, AdminEquipmentDetailView, UserRegisterView, \
    GymMembershipPaymentCreate, UserAdminDashBoardView, gym_equipment_order_ajax_view

from django.urls import path

urlpatterns = [
    path('superadmin/dashboard', SuperAdminDashBoardView.as_view(), name='superadmin_dashboard'),
    path('user/dashboard', UserAdminDashBoardView.as_view(), name='user_dashboard'),
    # superadmin section - GymCreation
    path('superadmin/gyminfo/create/', GymInformationCreateView.as_view(), name='superadmin_gym_create'),
    path('superadmin/gyminfo/update/<int:pk>', GymInformationUpdateView.as_view(), name='superadmin_gym_update'),
    path('superadmin/gyminfo/delete/<int:pk>', GymInfoDeleteView.as_view(), name='superadmin_gym_delete'),
    path('superadmin/gyminfo/list/', GymInformationListView.as_view(), name='superadmin_gym_list'),

    # Admin Section
    path('user/admin/create/<int:gym_id>', AdministratorCreateView.as_view(), name='fithub_admin_create'),
    path('user/admin/update/<int:pk>', AdministratorUpdateView.as_view(), name='fithub_admin_update'),
    path('user/admin/delete/<int:pk>', AdministratorDeleteView.as_view(), name='fithub_admin_delete'),
    path('user/admin/list/<int:gym_id>', AdministratorListView.as_view(), name='fithub_admin_list'),
    path('user/admin/dashboard', AdminDashBoardView.as_view(), name='fithub_admin_dashboard'),

    # Trainer Section
    path('user/trainer/create/', TrainerCreateView.as_view(), name='fithub_trainer_create'),
    path('user/trainer/update/<int:pk>', TrainerUpdateView.as_view(), name='fithub_trainer_update'),
    path('user/trainer/delete/<int:pk>', TrainerDeleteView.as_view(), name='fithub_trainer_delete'),
    path('user/trainer/list/', TrainerListView.as_view(), name='fithub_trainer_list'),
    path('user/trainer/dashboard', TrainerDashBoardView.as_view(), name='fithub_trainer_dashboard'),

    # Admin Video Management
    path('user/admin/video/create/', AdminVideoCreateView.as_view(), name='fithub_admin_video_create'),
    path('user/admin/video/update/<int:pk>', AdminVideoUpdateView.as_view(), name='fithub_admin_video_update'),
    path('user/admin/video/delete/<int:pk>', AdminVideoDeleteView.as_view(), name='fithub_admin_video_delete'),
    path('user/admin/video/list/', AdminVideoListView.as_view(), name='fithub_admin_video_list'),

    # Admin Blog Management
    path('user/admin/blog/create/', AdminBlogCreateView.as_view(), name='fithub_admin_blog_create'),
    path('user/admin/blog/update/<int:pk>', AdminBlogUpdateView.as_view(), name='fithub_admin_blog_update'),
    path('user/admin/blog/delete/<int:pk>', AdminBlogDeleteView.as_view(), name='fithub_admin_blog_delete'),
    path('user/admin/blog/detail/<int:pk>', AdminBlogDetailView.as_view(), name='fithub_admin_blog_detailview'),
    path('user/admin/blog/list/', AdminBlogListView.as_view(), name='fithub_admin_blog_list'),


    # Admin PaymentPlan Management
    path('user/admin/payment/plan/create/', AdminPaymentPlanCreateView.as_view(), name='fithub_admin_payment_plan_create'),
    path('user/admin/payment/plan/update/<int:pk>', AdminPaymentPlanUpdateView.as_view(), name='fithub_admin_payment_plan_update'),
    path('user/admin/payment/plan/delete/<int:pk>', AdminPaymentPlanDeleteView.as_view(), name='fithub_admin_payment_plan_delete'),
    path('user/admin/payment/plan/list/', AdminPaymentPlanListView.as_view(), name='fithub_admin_payment_plan_list'),

    # Add Gym Equipments
    path('user/admin/equipment/create/', AdminEquipmentCreateView.as_view(), name='fithub_admin_equipment_create'),
    path('user/admin/equipment/update/<int:pk>', AdminEquipmentUpdateView.as_view(), name='fithub_admin_equipment_update'),
    path('user/admin/equipment/delete/<int:pk>', AdminEquipmentDeleteView.as_view(), name='fithub_admin_equipment_delete'),
    path('user/admin/equipment/detail/<int:pk>', AdminEquipmentDetailView.as_view(), name='fithub_admin_equipment_detailview'),
    path('user/admin/equipment/list/', AdminEquipmentListView.as_view(), name='fithub_admin_equipment_list'),
    path('user/user/equipment/order_ajax_view/', gym_equipment_order_ajax_view, name='fithub_order_placed_for_equipment_ajax'),

    # User Payment
    path('user/payment/', GymMembershipPaymentCreate.as_view(), name='fithub_user_payment'),




    # Login Section
    path('register', UserRegisterView.as_view(), name='fithub_user_register_view'),
    path('', UserLogin.as_view(), name='fithub_login_view'),
    path('logout', LogoutView.as_view(), name='fithub_logout_view'),
    path('user/admins/change_password/', ChangePasswordView.as_view(), name='fithub_administrators_password_change'),



]

FitHub/FitHubManageApp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class FitHubMember(models.Model):
    Male = "Male"
    Female = "Female"
    Others = "Others"
    GenderChoices = (
        (Male, "Male"),
        (Female, "Female"),
        (Others, "Others"),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    sex = models.CharField(choices=GenderChoices, max_length=10, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    plan = models.ForeignKey('Plan', on_delete=models.CASCADE, null=True, blank=True)
    payment_status = models.BooleanField(default=False)
    joining_date = models.DateTimeField(auto_now=True)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    plan_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}"


class Plan(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    duration = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class GymInformation(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100, unique=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    instagram = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)
    logo = models.ImageField(upload_to='gym_information/', null=True, blank=True,
                             default='gym_information/logo.png')
    about_us = models.TextField(blank=True, null=True)
    members = models.ManyToManyField(User, related_name='gym_members', null=True, blank=True)

    def __str__(self):
        return self.name


class AdminGymGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='gym_gallery/', null=True, blank=True, default='gym_gallery/gym_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.name)


class GymMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    is_trainer = models.BooleanField(default=False)
    is_normal_member = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"


class GymAdministator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


class GymTrainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


class AdminVideoGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.name)


class Equipments(models.Model):
    name = models.CharField(max_length=512, default='')
    description = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='equipments/', null=True, blank=True, default='equipments/equipment_image.png')
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return "{}".format(self.name)


class EquipmentOrder(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='equipments/', null=True, blank=True, default='equipments/equipment_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    user = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now=True)


class Payment(models.Model):
    member = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    payment_date = models.DateTimeField(auto_now=True)
    plan = models.ForeignKey('Plan', on_delete=models.CASCADE)


class GymMemberVideoGallery(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.name)


class WorkoutVideo(models.Model):
    name = models.CharField(max_length=512, default='')
    url = models.CharField(max_length=512, default='')
    thumbnail = models.ImageField(upload_to='gym_video_gallery/', null=True, blank=True,
                                  default='gym_video_gallery/gym_video_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)


class DietChart(models.Model):
    name = models.CharField(max_length=512, default='')
    image = models.ImageField(upload_to='diet_chart/', null=True, blank=True, default='diet_chart/diet_chart_image.png')
    sort_order = models.PositiveIntegerField(default=0)
    gym_info = models.ForeignKey('GymInformation', on_delete=models.CASCADE)
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)
    member = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    diet_chart_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)


class Blog(models.Model):
    title = models.CharField(max_length=512)
    image = models.ImageField(upload_to='blog/', null=True, blank=True, default='blog/blog_image.png')
    admin = models.ForeignKey(GymAdministator, on_delete=models.CASCADE)
    description = models.TextField()
    blog_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.title)

class BuyEquipment(models.Model):
    count = models.IntegerField(default=1)
    user = models.ForeignKey('FitHubMember', on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now=True)
    equipment = models.ForeignKey('Equipments', on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.name)

FitHub/FitHubManageApp/templates/FitHubManageApp/Blog/admin_blog_add.html
{% extends 'adminlte/base.html' %}
{% block title %}Add Blog{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-warning">
                <div class="card-header">
                    <h3 class="card-title">Add Your Blog</h3>
                </div>

                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="form-group">
                                    <label for="id_title">Title</label>
                                    <input type="text" class="form-control" placeholder="Enter ..." id="id_title"
                                           name="title" required>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="form-group">
                                    <label for="id_description">Description</label>
                                    <textarea class="form-control" rows="10" placeholder="Enter ..." id="id_description"
                                              name="description" required></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">

                        <label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" id="id_image">

                    </div>{% comment %}

                                <div class="form-group">
                                    <div class="form-group">
                                        <label for="id_image">Add Image</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" id="id_image" name="image">
                                                <label class="custom-file-label" for="id_image"></label>
                                            </div>
                                            <div class="input-group-append">
                                                <span class="input-group-text">Upload</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>{% endcomment %}
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-warning">Submit</button>
                        </div>

                    </form>
                </div>


            </div>
        </div>
    </div>
{% endblock %}

FitHub/FitHubManageApp/templates/FitHubManageApp/Blog/admin_blog_delete.html
{% extends 'adminlte/base.html' %}
{% block title %}FitHub{% endblock %}
{% block content %}

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Blog Delete</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" action="">
            {% csrf_token %}
            <div class="card-body">
                <p>Are you sure you want to delete "{{ object }}" ?</p>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
    </div>
{% endblock %}

FitHub/FitHubManageApp/templates/FitHubManageApp/Blog/admin_blog_edit.html
{% extends 'adminlte/base.html' %}
{% block title %}video edit{% endblock %}
{% block content %}

    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Blog update</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" action="">
            {% csrf_token %}
            {#            {{ form.as_p }}#}
            <div class="card-body">
                {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

FitHub/FitHubManageApp/templates/FitHubManageApp/Blog/admin_blog_list.html
{% extends 'adminlte/base.html' %}
{% load user_tags %}
{% block title %}Blog List{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Blog List</h3>

            <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-hover text-nowrap">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Updated on</th>
                    <th>author</th>



                </tr>
                </thead>
                <tbody>
                {% for blog in admin_blog_list %}
                <tr>
                    <td>{{ blog.title}}</td>
                    <td>{{ blog.blog_date }}</td>
                    <td>{{ blog.admin }}</td>


                    <td><a href="{% url 'fithub_admin_blog_detailview' blog.id %}" type="button" class="btn btn-block btn-primary"><i class="fas fa-readme"></i>ReadMore</a></td>

                      {% if request.user|is_trainer or request.user|is_administrator %}
                    <td><a href="{%  url 'fithub_admin_blog_delete' blog.id %}" type="button" class="btn btn-block btn-danger">Delete</a></td>
                    {% endif %}
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>

{% endblock %}

FitHub/FitHubManageApp/templates/FitHubManageApp/Blog/blog_details.html
{% extends 'adminlte/base.html' %}
{% block content %}
    <div class="row text-center">
    <div class="col-md-12">

        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="https://www.seekpng.com/png/detail/966-9665317_placeholder-image-person-jpg.png" alt="User Image">
                    <span class="username"><a href="#">{{ object.admin }}</a></span>
                    <span class="description">Shared publicly - {{ object.blog_date}}</span>

                </div>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" title="Mark as read">
                        <i class="far fa-circle"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>

            </div>

            <div class="card-body">
                <img class="img-fluid pad text-center" src="{% if object.image %}{{ object.image.url }}{% else %}https://img.huffingtonpost.com/asset/5cd602f62500005500a47ed5.jpeg?ops=scalefit_720_noupscale&format=webp {% endif %}" alt="Photo" height="60%" width="60%">

            </div>

            <div class="card-footer card-comments">
                <div class="card-comment">

                    {% comment %}<img class="img-circle img-sm" src="../dist/img/user3-128x128.jpg" alt="User Image">{% endcomment %}
                    <div class="comment-text">
                        <span class="username">
                       {{ object.title }}
                       {% comment %} <span class="text-muted float-right">8:03 PM Today</span>{% endcomment %}
                        </span>
                        {{ object.description }}

                    </div>

                </div>



            </div>

            <div class="card-footer">

            </div>

        </div>

    </div>
    </div>
{% endblock %}